// <auto-generated />
using System;
using IntroEF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntroEF.Migrations
{
    [DbContext(typeof(TareasContext))]
    [Migration("20230625032432_datosDeInicio")]
    partial class datosDeInicio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IntroEF.Modelos.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("0ca6d57a-9817-4a6c-a80f-af672816a57f"),
                            Nombre = "Actividades Pendientes",
                            Peso = 20
                        },
                        new
                        {
                            CategoriaId = new Guid("5b080b9d-e620-4e11-9b9f-5ca932ff5fe3"),
                            Nombre = "Actividades Pendientes",
                            Peso = 30
                        });
                });

            modelBuilder.Entity("IntroEF.Modelos.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrioridadTarea")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("pruebaMigration")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("402606b1-801e-4e3c-bc74-257f6fb73009"),
                            CategoriaId = new Guid("0ca6d57a-9817-4a6c-a80f-af672816a57f"),
                            FechaCreacion = new DateTime(2023, 6, 24, 22, 24, 31, 970, DateTimeKind.Local).AddTicks(5142),
                            PrioridadTarea = 1,
                            Titulo = "Pago de Servicios Publicos"
                        },
                        new
                        {
                            TareaId = new Guid("c2aeeb3d-8037-4cda-9e46-8edbd10196cc"),
                            CategoriaId = new Guid("5b080b9d-e620-4e11-9b9f-5ca932ff5fe3"),
                            FechaCreacion = new DateTime(2023, 6, 24, 22, 24, 31, 970, DateTimeKind.Local).AddTicks(5159),
                            PrioridadTarea = 0,
                            Titulo = "Termina Cursos Platzi"
                        });
                });

            modelBuilder.Entity("IntroEF.Modelos.Tarea", b =>
                {
                    b.HasOne("IntroEF.Modelos.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("IntroEF.Modelos.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
